znap source lukechilds/zsh-nvm
znap source "z-shell/zsh-eza"
znap source ellie/atuin
znap source mattberther/zsh-pyenv
znap source ptavares/zsh-sdkman
znap source unixorn/fzf-zsh-plugin
znap source zpm-zsh/clipboard
znap source Atlas34/fzf-plugin
znap source mfaerevaag/wd