# Monokai Pro Filter Spectrum inspired Starship configuration

format = """
$os\
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$kubernetes\
$directory\
$vcsh\
$fossil_branch\
$fossil_metrics\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$pijul_channel\
$docker_context\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$gleam\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$quarto\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$typst\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$conda\
$meson\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$nats\
$direnv\
$env_var\
$crystal\
$custom\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time\
$status\
$container\
$shell\
$character"""

# Core
[character]
  error_symbol = "[](#ff6188)"
  success_symbol = "[](#a9dc76)"

[directory]
  read_only = " 󰌾"
  style = "fg:#ffd866"
  truncate_to_repo = false

[username]
  format = "[$user]($style) "
  show_always = false
  style_root = "fg:#ff6188"
  style_user = "fg:#78dce8"

[hostname]
  format = "[@$hostname]($style) "
  ssh_symbol = " "
  style = "fg:#ab9df2"

# Git
[git_branch]
  format = "[$symbol$branch]($style) "
  style = "fg:#ab9df2"
  symbol = " "

[git_status]
  format = '([\[$all_status$ahead_behind\]]($style) )'
  style = "fg:#fc618d"

[git_state]
  style = "fg:#ffd866"

[git_commit]
  style = "fg:#78dce8"
  tag_symbol = '  '

# Tools
[package]
  format = "[$symbol$version]($style) "
  style = "fg:#ffd866"
  symbol = "󰏗 "

[docker_context]
  format = "[$symbol$container]($style) "
  style = "fg:#78dce8"
  symbol = " "

# Utils
[cmd_duration]
  format = "[$duration]($style) "
  min_time = 500
  style = "fg:#78dce8"

[direnv]
  format = "[$symbol$env]($style) "
  style = "fg:#ffd866"
  symbol = " "

[os]
  disabled = false
  style = "fg:#fc618d"

[os.symbols]
  AlmaLinux = " "   # nf-linux-almalinux
  Alpine = " "      # nf-linux-alpine
  Android = " "     # nf-linux-android
  Arch = " "        # nf-linux-arch
  CentOS = " "      # nf-linux-centos
  Debian = " "      # nf-linux-debian  
  EndeavourOS = " " # nf-linux-endeavouros
  Fedora = " "      # nf-linux-fedora
  FreeBSD = " "     # nf-linux-freebsd
  Kali = " "        # nf-linux-kali
  Linux = " "       # nf-linux-linux
  Macos = " "       # nf-linux-macos
  Manjaro = " "     # nf-linux-manjaro
  Mint = "󰣭 "        # nf-linux-mint
  NixOS = "󱄅 "       # nf-linux-nixos
  OpenBSD = " "     # nf-linux-openbsd
  Pop = " "         # nf-linux-pop
  Raspbian = " "    # nf-linux-raspbian
  Ubuntu = " "      # nf-linux-ubuntu
  Unknown = " "     # nf-linux-unknown
  Windows = " "

[time]
  disabled = false
  format = ' [$time]($style) '
  style = "fg:#78dce8"
  time_format = "%H:%M:%S"

# Languages with symbols
[nodejs]
  style = "fg:#78dce8"
  symbol = ""

[rust]
  style = "fg:#fc618d"
  symbol = "󱘗"

[python]
  style = "fg:#ffd866"
  symbol = ""

[golang]
  style = "fg:#78dce8"
  symbol = ""

[php]
  style = "fg:#ab9df2"
  symbol = ""

[java]
  style = "fg:#fc618d"
  symbol = ""

[kotlin]
  style = "fg:#a9dc76"
  symbol = ""

[haskell]
  style = "fg:#ff6188"
  symbol = "λ"

[gradle]
  style = "fg:#ffd866"
  symbol = ""

[elixir]
  style = "fg:#fc618d"
  symbol = ""

[ruby]
  style = "fg:#a9dc76"
  symbol = ""

[c]
  style = "fg:#78dce8"
  symbol = ""

[swift]
  style = "fg:#ffd866"
  symbol = ""
